### ISSUE TITLE
Abstract satellite data in the Heap

### ISSUE THREAD

**Issue by QGarchery** [morpho-dao/morpho-data-structures#65]
We should also provide a way to abstract the satellite data in the structure, that way it can be reusable

_Originally posted by @QGarchery in https://github.com/morpho-dao/morpho-data-structures/issues/23#issuecomment-1186575374_

**Comment by Tristan22400** [comment]
I understand that it adds complexity for a non-substancial benefit. I will close the issue and the PR if you agree.
