### ISSUE TITLE
Create a folder with the previous heap version used by `morpho-v1`

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-dao/morpho-data-structures#92]
The storage layout has changed compared to the one used in `morpho-v1`. We must get back to this version if we want to apply changes to the deployed contracts.

**Comment by MerlinEgalite** [comment]
Yes, this can work too. But then it's more difficult to check the differences between the data structure used by Morpho and the one for general purposes.

**Comment by Rubilmax** [comment]
As long as you can compare 2 commits (which can be achieve via `git diff`), I don't understand how
> it's more difficult to check the differences between the data structure used by Morpho and the one for general purposes

Showing the diff between the branch of `morpho-v1` & `main` would do the trick? And it's not more difficult that comparing 2 files?

**Comment by MerlinEgalite** [comment]
But then on main, you'll never see the contract which is deployed which is weird IMO given what we decided for Morpho's contracts (and which is currently weird).

But ultimately, I think this is mainly for the research team to decide how they want to manage that @QGarchery @MathisGD

**Comment by Rubilmax** [comment]
> But then on main, you'll never see the contract which is deployed

Actually from GitHub's interface on `morpho-v1`, you have the full source (submodules links point to the repository referenced at the submodule's commit)

**Comment by QGarchery** [comment]
Both solutions are fine for me: 
- branches have the advantage of having main clean and up-to-date for users of the repository
- folders have the advantage of being able to factorize development, notably you don't have to do 2 PRs when you change the CI

I'll delegate my vote to @MathisGD :D

**Comment by MathisGD** [comment]
Both are ok to me, choose what's the simplest for you

**Comment by QGarchery** [comment]
Alright, let's go for a morpho-v1 branch then. It also has the nice property that if we want to modify something, we will know that we could potentially break morpho-v1 on the morpho-v1 branch

**Comment by MerlinEgalite** [comment]
> folders have the advantage of being able to factorize development, notably you don't have to do 2 PRs when you change the CI

This must be kept in mind. And if you introduce a new testing suite (like invariant and formal proving for instance) you'll need to replicate everything on the `morpho-v1`'s branch. 

@Rubilmax if you think it's better to have the branch then let's go
